---
all:
  hosts:
    production:
      ansible_host: 79.137.248.205
      ansible_user: root
      ansible_ssh_pass: {{ ansible_ssh_pass }}
      # Переопределение переменных для production
      frontend_image_tag: "v2.2.3"
      backend_image_tag: "v2.2.3"
      frontend_port: 8090
      backend_port: 5000
      nginx_domain: "stickystick.ru"
      project_path: "/opt/stickystick"

      # HTTP Basic Auth для защищенных локаций
      nginx_auth_username: ""  # Имя пользователя для HTTP Basic Auth
      nginx_auth_password: ""  # Пароль (рекомендуется использовать vault)

